###############################################################################
# go-what - .golangci.yml
# Copyright (c) 2016 MIT PDOS
# Copyright (c) 2025 Jeffrey H. Johnson
# SPDX-License-Identifier: MIT-0
# scspell-id: 6c37919e-83ca-11f0-a8d1-80ee73e9b8e7
###############################################################################

version: "2"
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - maintidx
    - mnd
    - nestif
    - noctx
    - varnamelen
    - wsl
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - golang.org/x/sys
            - golang.org/x/term
          deny:
            - pkg: io/ioutil
              desc: "Deprecated: see https://pkg.go.dev/io/ioutil for details"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: lax
    paths:
      - builtin$
      - examples$
      - third_party$
